<a href="https://colab.research.google.com/github/15IITian/git/blob/tensorflow/Tensorflow_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# if tf.config.list_physical_devices('GPU'):
#   print("TensorFlow **IS** using the GPU")
# else:
#   print("TensorFlow **IS NOT** using the GPU")

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
scalar=  tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vector= tf.constant([1,2,3,4])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
matrix = tf.constant(
[[1,2,3],
 [4,5,6],
 [7,8,9]]
 )
matrix


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix= tf.constant([[1.,2.,3.],
                             [4.,5.,6.]] , dtype= tf.float16)
another_matrix



<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)>

In [ ]:
tensor= tf.constant([[[[1,2,3],[4,5,6]],
  [[7,8,9],[1,2,3]]],
   [[[3,2,1],[4,3,2]],
    [[5,4,5],[5,5,4]]]])
tensor


<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
array([[[[1, 2, 3],
         [4, 5, 6]],

        [[7, 8, 9],
         [1, 2, 3]]],


       [[[3, 2, 1],
         [4, 3, 2]],

        [[5, 4, 5],
         [5, 5, 4]]]], dtype=int32)>

In [ ]:
tensor.ndim

4

In [ ]:
ch= tf.Variable([10,9])
unch= tf.constant([10,9])

In [ ]:
ch.assign([1,1])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([1, 1], dtype=int32)>

In [ ]:
ch.assign_add([1,1])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([2, 2], dtype=int32)>

In [ ]:
ch

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 2], dtype=int32)>

In [ ]:
ch[0].assign(1)
ch

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
random_1= tf.random.Generator.from_seed(42)
random_1= random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(41)
random_2= random_2.normal(shape=(3,2))



random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.31662667, -1.4391748 ],
        [ 0.58923835, -1.4268045 ],
        [-0.7565803 , -0.06854702]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

### Shuffling ->

In [ ]:
var= tf.constant([[1,2,3],[4,5,6], [12,13,14]])
var

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [12, 13, 14]], dtype=int32)>

In [ ]:
tf.random.shuffle(var)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [12, 13, 14]], dtype=int32)>

In [ ]:
tf.random.shuffle(var, seed =42)



<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[12, 13, 14],
       [ 4,  5,  6],
       [ 1,  2,  3]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(var, 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [12, 13, 14],
       [ 4,  5,  6]], dtype=int32)>

In [ ]:
tf.random.set_seed(100)
tf.random.shuffle(var)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[12, 13, 14],
       [ 1,  2,  3],
       [ 4,  5,  6]], dtype=int32)>

In [ ]:
tf.ones(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
import numpy as np
num_A= np.arange(1,25,  dtype= np.int32)
A=tf.constant(num_A, shape= (2,2,3,2))
num_A , A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 2, 3, 2), dtype=int32, numpy=
 array([[[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],
 
         [[ 7,  8],
          [ 9, 10],
          [11, 12]]],
 
 
        [[[13, 14],
          [15, 16],
          [17, 18]],
 
         [[19, 20],
          [21, 22],
          [23, 24]]]], dtype=int32)>)

In [ ]:
rank_4_tensor= tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.ndim

4

In [ ]:
print("Datatype of every element" , rank_4_tensor.dtype)
print("No of Dimensions" ,rank_4_tensor.ndim)
print("Shape of tensor, ",rank_4_tensor.shape)
print("Elemets along the axis=1 of tensor ", rank_4_tensor.shape[1])
print("Elemets along the last axis of tensor", rank_4_tensor.shape[-1])


Datatype of every element <dtype: 'float32'>
No of Dimensions 4
Shape of tensor,  (2, 3, 4, 5)
Elemets along the axis=1 of tensor  3
Elemets along the last axis of tensor 5


In [ ]:
rand=tf.random.Generator.from_seed(1234,alg="philox")
arr=rand.normal(shape=(3,3)).numpy()
arr



array([[ 0.9356609 ,  1.0854305 , -0.93788373],
       [-0.5061547 ,  1.3169702 ,  0.7137579 ],
       [-0.4126717 , -0.40257987,  2.0713255 ]], dtype=float32)

In [ ]:
# var=tf.random.Generator.from_seed(1234, alg="threefry")
# var.normal(shape=(3,3))

In [ ]:
# g = tf.random.Generator.from_non_deterministic_state( alg="threefry")
# g.normal(shape=(3,3))

In [ ]:
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))

tf.Tensor([0.76732683], shape=(1,), dtype=float32)
tf.Tensor([0.11529493], shape=(1,), dtype=float32)
tf.Tensor([0.10706615], shape=(1,), dtype=float32)
tf.Tensor([0.9289516], shape=(1,), dtype=float32)


In [ ]:
# tf.random.set_seed(123)
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))

tf.Tensor([0.4720682], shape=(1,), dtype=float32)
tf.Tensor([0.16123068], shape=(1,), dtype=float32)


In [ ]:
# tf.random.set_seed(12)
print(tf.random.uniform([1],seed=1))
print(tf.random.uniform([1],seed=1))



tf.Tensor([0.53493106], shape=(1,), dtype=float32)
tf.Tensor([0.8564223], shape=(1,), dtype=float32)


___________________________________________________________________________________________________________________________________________-

In [ ]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1,:1,2:3,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1,:1,:3,:3]

<tf.Tensor: shape=(1, 1, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor= tf.constant([[1,2],[3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
rank_2_tensor[-1,0:1]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>

In [ ]:
rank_2_tensor= tf.constant([[1,2],[3,4]])
rank_2_tensor
rank_3_tensor= rank_2_tensor[tf.newaxis,:]
rank_3_tensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 2]],

       [[3, 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=2)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

# Manipulating Tensors->

In [ ]:
tensor= tf.constant([[0,2],[3,4]])


In [ ]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 12],
       [13, 14]], dtype=int32)>

In [ ]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-10,  -8],
       [ -7,  -6]], dtype=int32)>

In [ ]:
tensor *  10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, 20],
       [30, 40]], dtype=int32)>

In [ ]:
tensor **  10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[      0,    1024],
       [  59049, 1048576]], dtype=int32)>

In [ ]:
tensor /  0

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[nan, inf],
       [inf, inf]])>

In [ ]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, 20],
       [30, 40]], dtype=int32)>

In [ ]:
tf.add(tensor, 10)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 12],
       [13, 14]], dtype=int32)>

In [ ]:
tf.subtract(tensor, 10)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-10,  -8],
       [ -7,  -6]], dtype=int32)>

In [ ]:
tf.divide(tensor, 10)


<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0. , 0.2],
       [0.3, 0.4]])>

## Matrix Multilplication->

In [ ]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [12, 22]], dtype=int32)>

In [ ]:
print(tensor)
tensor * tensor

tf.Tensor(
[[0 2]
 [3 4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0,  4],
       [ 9, 16]], dtype=int32)>

In [ ]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [12, 22]], dtype=int32)>

In [ ]:
x= tf

In [ ]:
x= tf.constant([[1,2],[2,3],[3,4]])
y= tf.constant([[4,5],[5,6],[6,7]])
x , y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 3],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[4, 5],
        [5, 6],
        [6, 7]], dtype=int32)>)

In [ ]:
# (3,2) * (3,2)

tf.matmul(tf.transpose(x) , y)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[32, 38],
       [47, 56]], dtype=int32)>

In [ ]:
tf.matmul(x, y , transpose_a= True, transpose_b= False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[32, 38],
       [47, 56]], dtype=int32)>

In [ ]:
tf.matmul(x, y , transpose_a = False, transpose_b= True)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[14, 17, 20],
       [23, 28, 33],
       [32, 39, 46]], dtype=int32)>

### reshape ->

In [ ]:
tf.reshape(y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 5, 5],
       [6, 6, 7]], dtype=int32)>

In [ ]:
print(x @ tf.reshape(y, shape=(2,3)).numpy())
print(x @ tf.transpose(y))

tf.Tensor(
[[16 17 19]
 [26 28 31]
 [36 39 43]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[14 17 20]
 [23 28 33]
 [32 39 46]], shape=(3, 3), dtype=int32)


In [ ]:
tf.tensordot(tf.transpose())

TypeError: ignored

In [ ]:
tf.__version__

In [ ]:
x= tf.constant([[1.,2.,3.],[4.,5.,6.]])
print(x)
print(x.shape)
print(x.dtype)

In [ ]:
x+ x


In [ ]:
 x @ tf.transpose(x)

In [ ]:
y= tf.constant([[1,1,1],[1,1,1]])
y

In [ ]:
tf.reduce_sum(x)

In [ ]:
tf.reduce_sum(x,1).numpy()

In [ ]:
tf.reduce_sum(x, keepdims=True)

In [ ]:
tf.convert_to_tensor([[[1,2],[3,3]],[[4,5],[6,7]]])

In [ ]:
var= tf.Variable([1,2,3,3])
var

In [ ]:
var[3].assign(0)

In [ ]:
var.assign_add([1,1,1,1])

# Doubt->

In [ ]:
var[3].assign_add([3])

________________________________________________________________________________

In [ ]:
# scalar
scalar=tf.constant(6)
vector= tf.constant([1,2,3,3])
matrix= tf.constant([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]])
# tensor #-> shape(2,4,2,2,1)
tensor= tf.constant([[[[[1],[2]],[[3],[4]]],[[[5],[6]],[[7],[8]]],[[[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]]]],[[[[17],[18]],[[19],[20]]],[[[21],[22]],[[23],[24]]],[[[25],[26]],[[27],[28]]],[[[29],[30]],[[31],[32]]]]])

In [ ]:
tensor.reduce_prod(tensor.shape)

AttributeError: ignored

In [ ]:
tf.reduce_prod(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=-2147483648>

In [ ]:
(tf.reduce_prod(tensor.shape)).numpy()

32

In [ ]:
(tensor.dtype).dtype

AttributeError: ignored

In [ ]:
def info(ten):
  print("shape of tensor:{} \n".format(ten.shape))
  print("size of tensor:{} \n".format((tf.reduce_prod(ten.shape)).numpy()))
  print("datatype of tensor:{} \n".format(ten.dtype))
  print("no of axis/rank of tensor:{} \n".format(ten.ndim))
  try :
    print("no of elements in last axis / dim  of tensor:{} \n".format(ten.shape[-1]))
  except:
    print("no of elements in last axis / dim  of tensor:{} \n".format(0))




In [ ]:
info(scalar)

shape of tensor:() 

size of tensor:1 

datatype of tensor:<dtype: 'int32'> 

no of axis/rank of tensor:0 

no of elements in last axis / dim  of tensor:0 



In [ ]:
info(vector)

shape of tensor:(4,) 

size of tensor:4 

datatype of tensor:<dtype: 'int32'> 

no of axis/rank of tensor:1 

no of elements in last axis / dim  of tensor:4 



In [ ]:
info(matrix)

shape of tensor:(2, 8) 

size of tensor:16 

datatype of tensor:<dtype: 'int32'> 

no of axis/rank of tensor:2 

no of elements in last axis / dim  of tensor:8 



In [ ]:
info(tensor)

shape of tensor:(2, 4, 2, 2, 1) 

size of tensor:32 

datatype of tensor:<dtype: 'int32'> 

no of axis/rank of tensor:5 

no of elements in last axis / dim  of tensor:1 



In [ ]:
a=tf.random.Generator.from_seed(123)
t1= a.uniform(shape=(5,300))
t1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.65647066, 0.30283117, 0.18523741, ..., 0.86160827, 0.505566  ,
        0.8621572 ],
       [0.6242349 , 0.5667416 , 0.08933961, ..., 0.6782286 , 0.6932179 ,
        0.5777626 ],
       [0.95516586, 0.01184368, 0.5583087 , ..., 0.6503265 , 0.92341375,
        0.68137383],
       [0.4698242 , 0.9976375 , 0.27073598, ..., 0.35579598, 0.55311036,
        0.08575082],
       [0.98145294, 0.7378117 , 0.16731274, ..., 0.46515346, 0.26577473,
        0.33852804]], dtype=float32)>

In [ ]:
t2= a.uniform(shape=(5,300))
t2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.8634263 , 0.9479408 , 0.40186977, ..., 0.43964934, 0.77066445,
        0.84274256],
       [0.80819035, 0.5346676 , 0.96623564, ..., 0.59659636, 0.9821116 ,
        0.84692764],
       [0.13327432, 0.30399787, 0.18289328, ..., 0.90298426, 0.6532866 ,
        0.0819484 ],
       [0.6427969 , 0.8915484 , 0.91348934, ..., 0.5364473 , 0.4295293 ,
        0.5687958 ],
       [0.83980227, 0.28973246, 0.22581995, ..., 0.22637641, 0.9677429 ,
        0.34467125]], dtype=float32)>

In [ ]:
t1, t2, t1==t2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.65647066, 0.30283117, 0.18523741, ..., 0.86160827, 0.505566  ,
         0.8621572 ],
        [0.6242349 , 0.5667416 , 0.08933961, ..., 0.6782286 , 0.6932179 ,
         0.5777626 ],
        [0.95516586, 0.01184368, 0.5583087 , ..., 0.6503265 , 0.92341375,
         0.68137383],
        [0.4698242 , 0.9976375 , 0.27073598, ..., 0.35579598, 0.55311036,
         0.08575082],
        [0.98145294, 0.7378117 , 0.16731274, ..., 0.46515346, 0.26577473,
         0.33852804]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.5173956 , 0.70992315, 0.59254336, ..., 0.13532805, 0.67974293,
         0.36152315],
        [0.61961794, 0.7251115 , 0.48358274, ..., 0.45402873, 0.6856811 ,
         0.6140553 ],
        [0.49002945, 0.320701  , 0.94886625, ..., 0.21973765, 0.3839898 ,
         0.59791327],
        [0.6690408 , 0.44956183, 0.7159374 , ..., 0.02988112, 0.61158586,
         0.9153842 ],
        [0.50856

In [ ]:
c=t1 @ tf.transpose(t2)
d= tf.matmul(t1, tf.transpose(t2))
c==d

<tf.Tensor: shape=(5, 5), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])>

In [ ]:
e=t1 @ tf.reshape(t2 , shape=(300,5))
f= tf.matmul(t1, tf.reshape(t2, shape=(300,5)))
e==f

<tf.Tensor: shape=(5, 5), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])>

In [ ]:
tf.tensordot(t1,t2, axes=0).shape

TensorShape([5, 300, 5, 300])

In [ ]:
start = 3
limit = 18
delta = 3
tf.range(start, limit, delta)



In [ ]:
# Method-1
start=0
limit=1
delta=1 / (224*224*3)

a=tf.reshape(tf.range(start, limit, delta) , shape=(224,224,3))
a.shape

TensorShape([224, 224, 3])

In [ ]:
a

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.0000000e+00, 6.6432822e-06, 1.3286564e-05],
        [1.9929847e-05, 2.6573129e-05, 3.3216413e-05],
        [3.9859693e-05, 4.6502973e-05, 5.3146257e-05],
        ...,
        [4.4044959e-03, 4.4111395e-03, 4.4177826e-03],
        [4.4244258e-03, 4.4310694e-03, 4.4377125e-03],
        [4.4443556e-03, 4.4509992e-03, 4.4576423e-03]],

       [[4.4642854e-03, 4.4709290e-03, 4.4775722e-03],
        [4.4842153e-03, 4.4908589e-03, 4.4975020e-03],
        [4.5041451e-03, 4.5107887e-03, 4.5174318e-03],
        ...,
        [8.8687818e-03, 8.8754250e-03, 8.8820681e-03],
        [8.8887112e-03, 8.8953553e-03, 8.9019984e-03],
        [8.9086415e-03, 8.9152846e-03, 8.9219278e-03]],

       [[8.9285709e-03, 8.9352150e-03, 8.9418581e-03],
        [8.9485012e-03, 8.9551443e-03, 8.9617874e-03],
        [8.9684306e-03, 8.9750746e-03, 8.9817178e-03],
        ...,
        [1.3333067e-02, 1.3339710e-02, 1.3346354e-02],
        [1.3352998e-02

In [ ]:
# Method-2
b= tf.random.get_global_generator()

b.normal(shape=(224,224,3))% 1


<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.74547875, 0.64436245, 0.8497162 ],
        [0.57159865, 0.99577737, 0.29317045],
        [0.21621686, 0.7758781 , 0.35531467],
        ...,
        [0.5287932 , 0.8020197 , 0.10175902],
        [0.33256653, 0.13362384, 0.8074783 ],
        [0.41193974, 0.04515523, 0.59567136]],

       [[0.8209652 , 0.17500572, 0.69381285],
        [0.92625225, 0.81844485, 0.09260748],
        [0.08713627, 0.10087341, 0.2141546 ],
        ...,
        [0.3209623 , 0.26274884, 0.87817377],
        [0.09577954, 0.16712306, 0.732353  ],
        [0.40773058, 0.7177696 , 0.19847769]],

       [[0.03877266, 0.9249064 , 0.00173656],
        [0.49742478, 0.03753331, 0.9071518 ],
        [0.43739748, 0.0256373 , 0.6554699 ],
        ...,
        [0.76294446, 0.17868386, 0.65612644],
        [0.20215583, 0.75977147, 0.56423783],
        [0.47923243, 0.8812351 , 0.7277894 ]],

       ...,

       [[0.2537639 , 0.90725815, 0.8233819 ],
        [0.68